version: "3"

services:
  bff:
    image: "nestjs-restaurant/bff"
    restart: always
    ports:
      - 4100:4100
    environment:
      - GATEWAY_URL_WITH_PORT=${GATEWAY}
    networks:
      - nestjs-restaurant-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  nestjs-restaurant-network:
    driver: bridge
