version: "3"

services:
  bff:
    image: "nestjs-restaurant/bff"
    restart: always
    ports:
      - 4100:4100
    environment:
      - GATEWAY_URL_WITH_PORT=${GATEWAY}
      - DB_URL=${DB_URL}
    depends_on:
      - postgres
    networks:
      - nestjs-restaurant-network
    volumes:
      - ./db-init:/db-init
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bffdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-restaurant-network

networks:
  nestjs-restaurant-network:
    driver: bridge

volumes:
  postgres_data:
